baseurl: "/"
languageCode: "en-us"
title: "Boris Lebedenko"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Projects
      url: "projects/"
      weight: 3
    - name: Resources
      url: "resources/"
      weight: 4
    - name: Consulting
      url: "consulting/"
      weight: 5
    - name: CV
      url: "cv/"
      weight: 6
    - name: Contact
      url: "contact/"
      weight: 7

params:
  description: "My personal blog and site. Igal, if you are reading this - stop editing sites' scripts and get back to work!"
  footer: "&copy; Boris Lebedenko"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
